In [4]:
##page 11
import numpy as np

In [5]:
## page 12
array_1d = np.array([61,52.5,71,32.5,68,64]) #this is a 1D array
array_2d = np.array([[18,26,17],
                     [25,15.5,12],
                     [24,27,20],
                     [10,5.5,17],
                     [27,26,15],
                     [22,21,21],
                    ])                       #this is a 2D array

In [6]:
print(type(array_1d))
print(type(array_2d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
## page 15 - 19
# 1 dimension array
print('Dimension Number: ', array_1d.ndim)
print('Array Shape: ', array_1d.shape)
print('Number Of data items: ', array_1d.size)
print('Data type of items: ', array_1d.dtype)

Dimension Number:  1
Array Shape:  (6,)
Number Of data items:  6
Data type of items:  float64


In [9]:
## page 20 - 25
# 2 dimension array
print('Dimension Number: ', array_2d.ndim)
print('Array Shape: ', array_2d.shape)
print('Number Of data items: ', array_2d.size)
print('Data type of items: ', array_2d.dtype)

Dimension Number:  2
Array Shape:  (6, 3)
Number Of data items:  18
Data type of items:  float64


In [11]:
## page 26
ones_2d = np.ones(shape=(3,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
zeros_1d = np.zeros(shape=5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [16]:
range_array = np.arange(2, 5, 0.5)
range_array

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
## page 27 - 32
print(array_1d[1])
print(array_2d[0,1])
print(array_1d[2:])
print(array_2d[3:,:])
print(array_2d[[0,2,1]])

52.5
26.0
[71.  32.5 68.  64. ]
[[10.   5.5 17. ]
 [27.  26.  15. ]
 [22.  21.  21. ]]
[[18.  26.  17. ]
 [24.  27.  20. ]
 [25.  15.5 12. ]]


In [22]:
##page 33 - 36
array_2d[2,:] = np.array([25,28,21])
array_2d

array([[18. , 26. , 17. ],
       [25. , 15.5, 12. ],
       [25. , 28. , 21. ],
       [10. ,  5.5, 17. ],
       [27. , 26. , 15. ],
       [22. , 21. , 21. ]])

In [23]:
array_1d[2] = 74
array_1d

array([61. , 52.5, 74. , 32.5, 68. , 64. ])

In [25]:
## page 37 - 38
# element wise aritmetic operations
array_2d = np.array([ [1,2] , [2,3.5], [5,6.5] ] )
print(array_2d + 3)
print(array_2d * 2)
print(array_2d + array_2d)
print(array_2d * array_2d)

[[4.  5. ]
 [5.  6.5]
 [8.  9.5]]
[[ 2.  4.]
 [ 4.  7.]
 [10. 13.]]
[[ 2.  4.]
 [ 4.  7.]
 [10. 13.]]
[[ 1.    4.  ]
 [ 4.   12.25]
 [25.   42.25]]


In [29]:
## page 39 - 42
## usd to sgd exercise
usd = [2,3.6,2.05,13.5,18.9]
exchange_rate = 1.37

usd_array = np.array(usd)
sgd_array = usd_array * exchange_rate

print("usd array")
print(usd_array)
print()
print("sgd array")
print(sgd_array)

usd array
[ 2.    3.6   2.05 13.5  18.9 ]

sgd array
[ 2.74    4.932   2.8085 18.495  25.893 ]


In [31]:
# page 44 - 49
# using the "distr"
# find
# 1. the expected newspaper demands
# 2. standard deviations of newspaper demands
# 3. the expected total profit with the given parameters

distr = np.array([[0.315,0.226,0.289,0.087,0.083],
                  [560,530,389,202,278],
                  [533,486,386,234,263],
                 ])   

In [36]:
# paper1 data result
exp1 = np.sum(distr[0] * distr[1])
var1 = np.sum(distr[0] * (distr[1] - exp1) ** 2)
std1 = var1 ** 0.5

print("Expected demand: {0:0.3f}".format(exp1))
print("Standard deviation: {0:0.3f}".format(std1))

Expected demand: 449.249
Standard deviation: 118.908


In [ ]:
# page 50
# can try out on your own...


In [44]:
cost = np.array([0.6,0.8])
price = np.array([1.0,1.15])
order = np.array([430,480])

exp_sold = np.sum(distr[0] * np.minimum(order[0], distr[1]))
distr[0] * np.minimum(order[0], distr[1])

array([135.45 ,  97.18 , 112.421,  17.574,  23.074])

In [ ]:
#stop at page 51